### ISSUE TITLE
Error: certificate has expired

### ISSUE THREAD

**Issue by AnasAlamin** [hyperledger/aries-acapy-plugin-toolbox#98]
i'm trying to run the demo agents on Aries-toolbox but i keep getting the below error
```
Error: certificate has expired
```
how can i fix this?!

**Comment by dbluhm** [comment]
This is caused by a recent expiration of an old Let's Encrypt root certificate. You can find more details here: https://github.com/hyperledger/aries-toolbox/issues/237

We are currently working to address this issue but I do not yet have a simple fix. I will post an update here when I have one. Thank you for your patience!

**Comment by frostyfrog** [comment]
With the recent merge of PR #114, does using the local container resolve the issues that you were having, @AnasAlamin?

**Comment by GavinBendixsen** [comment]
I ran into the same issue when running the demo agents, and using the local container resolved the issue.

**Comment by frostyfrog** [comment]
With the merge of hyperledger/aries-toolbox#252, I believe that this is now working and resolved.
